name: Deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
    - uses: actions/checkout@v2
    - name: Export SSH private key
      run: echo "$SSH_PRIVATE_KEY" > id_rsa && chmod 600 id_rsa
      env:
        SSH_PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
    - name: Deploy
      run: |
        scp -r\
            -o 'StrictHostKeyChecking no'\
            -o UserKnownHostsFile=/dev/null\
            -P ${{ secrets.SSH_PORT }}\
            -i id_rsa\
            ./bikikimk2-net/\
            ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }}:${{ secrets.SCP_TARGET }}

